---
kind: pipeline
name: caddy

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: titouanco/caddy
    tags: latest
    username:
      from_secret: docker_username

---
kind: pipeline
name: caddy-cache

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    build_args:
    - CADDY_FEATURES=http.cache
    password:
      from_secret: docker_password
    repo: titouanco/caddy
    tags: cache
    username:
      from_secret: docker_username

...
